django-dashboard-kit/apps/home/urls.py
from django.urls import path, include
from django.shortcuts import redirect
from rest_framework.routers import DefaultRouter
from .views import ( IndexView, ClienteListView, ClienteDetailView, lista_atividades,
    adicionar_atividade, excluir_atividade, editar_atividade,
    adicionar_cliente, ServicoCreateView, editar_servico, ServicoDeleteView,
    ProjectCreateView, ProjectListView, ProjectUpdateView, ProjectDeleteView
)
from .views_api import (
    CompanyViewSet, TipoServicoViewSet, StatusViewSet,
    ClienteViewSet, ServicoViewSet, AtividadeViewSet
)

app_name = 'home'

# Criar um roteador para as rotas da API
router = DefaultRouter()
router.register(r'companies', CompanyViewSet)
router.register(r'tipo-servicos', TipoServicoViewSet)
router.register(r'status', StatusViewSet)
router.register(r'clientes', ClienteViewSet)
router.register(r'servicos', ServicoViewSet)
router.register(r'atividades', AtividadeViewSet)

urlpatterns = [
    # Rotas da web
    path('', lambda request: redirect('ligobots:dashboard_kpi_ura'), name='home'),
    path('lista_clientes/', ClienteListView.as_view(), name='lista_clientes'),
    path('detalhe_cliente/<int:pk>/', ClienteDetailView.as_view(), name='detalhe_cliente'),

    path('cliente/<int:cliente_id>/atividades/', lista_atividades, name='lista_atividades'),
    path('cliente/<int:cliente_id>/atividade/adicionar/', adicionar_atividade, name='adicionar_atividade'),
    path('cliente/<int:cliente_id>/atividade/<int:atividade_id>/excluir/', excluir_atividade, name='excluir_atividade'),
    path('cliente/<int:cliente_id>/atividade/<int:atividade_id>/editar/', editar_atividade, name='editar_atividade'),

    path('clientes/adicionar/', adicionar_cliente, name='adicionar_cliente'),

    path('servico/editar/<int:id>/', editar_servico, name='editar_servico'),
    path('cliente/<int:cliente_id>/servico/adicionar/', ServicoCreateView.as_view(), name='adicionar_servico'),
    path('cliente/<int:cliente_id>/servico/<int:pk>/excluir/', ServicoDeleteView.as_view(), name='excluir_servico'),

    path('projetos/', ProjectListView.as_view(), name='lista_projetos'),
    path('projetos/add/', ProjectCreateView.as_view(), name='adicionar_projeto'),
    path('projeto/<int:pk>/editar/', ProjectUpdateView.as_view(), name='editar_projeto'),
    path('projeto/<int:pk>/excluir/', ProjectDeleteView.as_view(), name='excluir_projeto'),

    # Rotas da API
    path('api/', include(router.urls)),
]

django-dashboard-kit/core/urls.py
# -*- encoding: utf-8 -*-

from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),          
    path("", include("apps.authentication.urls")), 
    path("", include("apps.home.urls")),
    path('ligobots/', include('apps.ligobots.urls', namespace='ligobots')),
    path('relatorios/', include('apps.relatorios.urls', namespace='relatorios')),
    path('analise-pico/', include('apps.analise_pico.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

django-dashboard-kit/apps/home/models.py
from django.db import models
from django.utils.text import slugify


# Modelo da Empresa
class Company(models.Model):
    name = models.CharField(max_length=255)

    def __str__(self):
        return self.name

# Modelo de Tipo de Serviço
class TipoServico(models.Model):
    nome = models.CharField(max_length=50)

    def __str__(self):
        return self.nome

# Modelo de Status
class Status(models.Model):
    nome = models.CharField(max_length=50)

    def __str__(self):
        return self.nome
    
class StatusProject(models.Model):
    name = models.CharField(max_length=255, unique=True)
    slug = models.SlugField(unique=True, blank=True, null=True)

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.name)
        super().save(*args, **kwargs)

    def __str__(self):
        return self.name
    
class Project(models.Model):

    PRIORITY_CHOICES = [
        ('Baixa', 'Baixa'),
        ('Média', 'Média'),
        ('Alta', 'Alta'),
    ]

    name = models.CharField(max_length=255)
    status = models.ForeignKey(StatusProject, on_delete=models.SET_NULL, null=True, blank=True)
    client = models.ForeignKey('Cliente', on_delete=models.PROTECT, related_name='projects')
    priority = models.CharField(max_length=10, choices=PRIORITY_CHOICES, default='Média')
    responsavel = models.CharField(max_length=255, default='Não atribuído')
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    data_entrega = models.DateTimeField(null=True, blank=True) 

    def __str__(self):
        return self.name



# Modelo de Cliente
class Cliente(models.Model):
    company = models.ForeignKey(Company, on_delete=models.PROTECT)
    nome = models.CharField(max_length=255)
    slug = models.SlugField(unique=True, blank=True, null=True)
    descricao = models.TextField(blank=True, null=True)
    criado_em = models.DateTimeField(auto_now_add=True)
    atualizado_em = models.DateTimeField(auto_now=True)
    foto = models.ImageField(upload_to='clientes/', blank=True, null=True)


    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.nome)
        super().save(*args, **kwargs)

    def __str__(self):
        return self.nome

# Modelo de Serviço
class Servico(models.Model):
    tipo = models.ForeignKey(TipoServico, on_delete=models.CASCADE)
    descricao = models.TextField(blank=True, null=True)
    criado_em = models.DateTimeField(auto_now_add=True)
    atualizado_em = models.DateTimeField(auto_now=True)
    cliente = models.ForeignKey(Cliente, related_name='servicos', on_delete=models.CASCADE, null=True, blank=True)

    def __str__(self):
        tipo_nome = self.tipo.nome if self.tipo else "Sem Tipo"
        cliente_nome = self.cliente.nome if self.cliente else "Sem Cliente"
        return f"{tipo_nome} - {cliente_nome}"


# Modelo de Atividade
class Atividade(models.Model):
    cliente = models.ForeignKey(Cliente, related_name='atividades', on_delete=models.CASCADE)
    descricao = models.TextField()
    status = models.ForeignKey(Status, on_delete=models.CASCADE)
    criado_em = models.DateTimeField(auto_now_add=True)
    atualizado_em = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f"{self.descricao} - {self.status.nome}"

django-dashboard-kit/apps/home/views.py
# -*- encoding: utf-8 -*-

import logging

from django.contrib.auth.decorators import login_required
from django.urls import reverse
from django.shortcuts import render, get_object_or_404, redirect
from django.urls import reverse_lazy
from django.views.generic import CreateView, UpdateView, DeleteView, ListView
from .forms import AtividadeForm, ServicoForm, ProjectForm, StatusProjectForm, ClienteFilterForm
from .models import Cliente, Servico, Atividade, TipoServico, Company, Project, StatusProject
from django.views.generic import TemplateView
from django.contrib import messages
from django.utils.decorators import method_decorator
from django.views.generic import DetailView
from django.contrib.auth.mixins import LoginRequiredMixin

logger = logging.getLogger(__name__)


@method_decorator(login_required, name='dispatch')
class ClienteListView(ListView):
    model = Cliente
    template_name = 'home/lista_clientes.html'
    context_object_name = 'clientes'
    paginate_by = 8

    def get_queryset(self):
        queryset = Cliente.objects.all()
        nome = self.request.GET.get('nome')
        descricao = self.request.GET.get('descricao')
        servico = self.request.GET.get('servico')
        if nome:
            queryset = queryset.filter(nome__icontains=nome)
        if descricao:
            queryset = queryset.filter(descricao__icontains=descricao)
        if servico:
            queryset = queryset.filter(servicos__tipo_id=servico)
        return queryset.distinct()

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['filter_form'] = ClienteFilterForm(self.request.GET or None)
        return context


@method_decorator(login_required, name='dispatch')
class IndexView(TemplateView):
    template_name = 'home/index.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        total_clientes = Cliente.objects.count()
        tipos_servico = TipoServico.objects.all()

        total_servicos_dict = {tipo.nome: Servico.objects.filter(tipo=tipo).count() for tipo in tipos_servico}
        total_servicos = sum(total_servicos_dict.values())
        servicos_recentes = Servico.objects.order_by('-criado_em')[:10]
        
        # Dados para gráficos
        clientes = list(Cliente.objects.values_list('nome', flat=True))  # Convertendo para lista
        servicos_por_cliente = [cliente.servicos.count() for cliente in Cliente.objects.all()]
        
        # Calcular porcentagem de cada tipo de serviço
        porcentagem_por_tipo = {
            tipo: (quantidade / total_servicos) * 100 for tipo, quantidade in total_servicos_dict.items()
        }

         # Criar lista com cliente, total de serviços e tipo mais comum
        clientes_servicos = []
        for cliente in Cliente.objects.all():
            total_servicos_cliente = cliente.servicos.count()
            tipos_servicos = ", ".join(cliente.servicos.values_list('tipo__nome', flat=True).distinct())
            clientes_servicos.append((cliente.nome, total_servicos_cliente, tipos_servicos))

        context.update({
            'total_clientes': total_clientes,
            'total_servicos': total_servicos,
            'total_servicos_dict': total_servicos_dict,
            'servicos_recentes': servicos_recentes,
            'clientes': clientes,  # Passando diretamente para o template
            'servicos_por_cliente': servicos_por_cliente,  # Passando diretamente para o template
            'clientes_servicos': clientes_servicos,
            'porcentagem_por_tipo_labels': list(porcentagem_por_tipo.keys()),  # Nomes dos tipos de serviço
            'porcentagem_por_tipo_values': list(porcentagem_por_tipo.values()),  # Percentagens por tipo
        })

        return context



class ClienteDetailView(LoginRequiredMixin, DetailView):
    model = Cliente
    template_name = 'home/detalhe_cliente.html'
    context_object_name = 'cliente'
    login_url = '/login/'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        cliente = self.get_object()
        context['servicos'] = cliente.servicos.all()
        return context

@method_decorator(login_required, name='dispatch')
class ProjectCreateView(CreateView):
    model = Project
    form_class = ProjectForm
    template_name = 'home/adicionar_projeto_modal.html'
    success_url = reverse_lazy('home:lista_projetos')

    def form_valid(self, form):
        cliente_id = self.request.POST.get('client')
        if not cliente_id:
            messages.error(self.request, "Cliente não informado.")
            return self.form_invalid(form)
        
        cliente = get_object_or_404(Cliente, id=cliente_id)
        form.instance.client = cliente
        messages.success(self.request, "Projeto adicionado com sucesso!")
        return super().form_valid(form)


@method_decorator(login_required, name='dispatch')
class ProjectUpdateView(UpdateView):
    model = Project
    form_class = ProjectForm
    template_name = 'home/editar_projeto_modal.html'
    success_url = reverse_lazy('home:lista_projetos')

    def form_valid(self, form):
        form.instance.client_id = self.request.POST.get('client')
        form.instance.priority = self.request.POST.get('priority')
        return super().form_valid(form)


@method_decorator(login_required, name='dispatch')
class ProjectDeleteView(DeleteView):
    model = Project
    template_name = 'home/excluir_projeto.html'
    success_url = reverse_lazy('home:lista_projetos')

    def delete(self, request, *args, **kwargs):
        messages.success(self.request, "Projeto excluído com sucesso!")
        return super().delete(request, *args, **kwargs)

@method_decorator(login_required, name='dispatch')
class ProjectListView(ListView):
    model = Project
    template_name = 'home/lista_projetos.html'
    context_object_name = 'projetos'
    paginate_by = 10

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['status_projetos'] = StatusProject.objects.all()
        context['clientes'] = Cliente.objects.all()
        context['form'] = ProjectForm()
        return context

@login_required(login_url="/login/")
def lista_atividades(request, cliente_id):
    cliente = get_object_or_404(Cliente, pk=cliente_id)
    atividades = cliente.atividades.all()
    
    date_range = request.GET.get('date_range')
    atividades_encontradas = True
    
    if date_range:
        try:
            if ' até ' in date_range:
                start_date, end_date = date_range.split(' até ')
            else:
                start_date = end_date = date_range

            atividades = atividades.filter(criado_em__date__range=[start_date, end_date])
            if not atividades.exists():
                atividades_encontradas = False
        except ValueError:
            atividades = cliente.atividades.all()  # Fallback para todas as atividades se o formato estiver incorreto
            atividades_encontradas = True

    return render(request, 'home/lista_atividades.html', {
        'cliente': cliente,
        'atividades': atividades,
        'atividades_encontradas': atividades_encontradas,
        'date_range': date_range
    })


@login_required(login_url="/login/")
def adicionar_atividade(request, cliente_id):
    cliente = get_object_or_404(Cliente, id=cliente_id)
    if request.method == 'POST':
        form = AtividadeForm(request.POST)
        if form.is_valid():
            atividade = form.save(commit=False)
            atividade.cliente = cliente
            atividade.save()
            return redirect('home:lista_atividades', cliente_id=cliente.id)
    else:
        form = AtividadeForm()
    return render(request, 'home/adicionar_atividade.html', {'form': form, 'cliente': cliente})

@login_required(login_url="/login/")
def excluir_atividade(request, cliente_id, atividade_id):
    atividade = get_object_or_404(Atividade, pk=atividade_id, cliente_id=cliente_id)
    atividade.delete()
    return redirect('home:lista_atividades', cliente_id=cliente_id)


@login_required(login_url="/login/")
def editar_atividade(request, cliente_id, atividade_id):
    cliente = get_object_or_404(Cliente, id=cliente_id)
    atividade = get_object_or_404(Atividade, id=atividade_id)
    
    if request.method == 'POST':
        form = AtividadeForm(request.POST, instance=atividade)
        if form.is_valid():
            atividade = form.save(commit=False)
            status_value = form.cleaned_data['status']
            atividade.status = status_value
            atividade.save()
            return redirect('home:lista_atividades', cliente_id=cliente.id)
    else:
        form = AtividadeForm(instance=atividade)
    
    return render(request, 'home/editar_atividade.html', {'form': form, 'cliente': cliente, 'atividade': atividade})

@login_required(login_url="/login/")
def adicionar_cliente(request):
    companies = Company.objects.all()
    tipos_servico = TipoServico.objects.all()
    if request.method == 'POST':
        nome = request.POST.get('nome')
        descricao = request.POST.get('descricao')
        foto = request.FILES.get('foto')
        tipo_servico_id = request.POST.get('tipo_servico')
        company_id = request.POST.get('company')
        
        if not company_id:
            messages.error(request, "Por favor, selecione uma empresa.")
            return render(request, 'home/adicionar_cliente.html', {'companies': companies, 'tipos_servico': tipos_servico})
        
        company = Company.objects.get(id=company_id)

        cliente = Cliente(nome=nome, descricao=descricao, foto=foto, company=company)
        cliente.save()

        # Buscar a instância do tipo de serviço pelo ID
        tipo_servico = TipoServico.objects.get(id=tipo_servico_id)
        
        # Adicione o tipo de serviço
        servico = Servico(cliente=cliente, tipo=tipo_servico)
        servico.save()

django-dashboard-kit/apps/templates/home/adicionar_cliente.html
{% extends "layouts/base.html" %}

{% block title %}Adicionar Cliente{% endblock %}

{% block content %}
<div class="pc-container">
    <div class="pcoded-content">
        <div class="page-header">
            <div class="page-block">
                <div class="row align-items-center">
                    <div class="col-md-6">
                        <div class="page-header-title">
                            <h5 class="m-b-10">Adicionar Cliente</h5>
                        </div>
                        <ul class="breadcrumb">
                            <li class="breadcrumb-item"><a href="{% url 'home:home' %}">Home</a></li>
                            <li class="breadcrumb-item"><a href="{% url 'home:lista_clientes' %}">Clientes</a></li>
                            <li class="breadcrumb-item active">Adicionar Cliente</li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
        <div class="row justify-content-center">
            <div class="col-md-8">
                <div class="card shadow-lg border-0 rounded-lg">
                    <div class="card-body">
                        {% if messages %}
                            <div class="container mt-4">
                                {% for message in messages %}
                                    <div class="alert {% if message.tags %}alert-{{ message.tags }}{% else %}alert-info{% endif %} alert-dismissible fade show" role="alert">
                                        {{ message }}
                                        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                            <span aria-hidden="true">&times;</span>
                                        </button>
                                    </div>
                                {% endfor %}
                            </div>
                        {% endif %}
                        <form method="post" enctype="multipart/form-data">
                            {% csrf_token %}
                            <div class="form-group mb-3">
                                <label for="id_company">Empresa:</label>
                                <select name="company" class="form-control" id="id_company" required>
                                    <option value="" disabled selected>Selecione a empresa</option>
                                    {% for company in companies %}
                                        <option value="{{ company.id }}">{{ company.name }}</option>
                                    {% endfor %}
                                </select>
                            </div>
                            <div class="form-group mb-3">
                                <label for="id_nome">Nome:</label>
                                <input type="text" name="nome" class="form-control" id="id_nome" placeholder="Digite o nome do cliente" required>
                            </div>
                            <div class="form-group mb-3">
                                <label for="id_descricao">Descrição:</label>
                                <textarea name="descricao" class="form-control" id="id_descricao" placeholder="Digite a descrição do cliente" rows="4" required></textarea>
                            </div>
                            <div class="form-group mb-3">
                                <label for="id_foto">Foto:</label>
                                <input type="file" name="foto" class="form-control-file" id="id_foto">
                            </div>
                            <div class="form-group mb-4">
                                <label for="id_tipo_servico">Tipo de Serviço:</label>
                                <select name="tipo_servico" class="form-control" id="id_tipo_servico" required>
                                    <option value="" disabled selected>Selecione o tipo de serviço</option>
                                    {% for tipo in tipos_servico %}
                                        <option value="{{ tipo.id }}">{{ tipo.nome }}</option>
                                    {% endfor %}
                                </select>
                            </div>
                            <div class="form-group text-center">
                                <button type="submit" class="btn btn-primary btn-block">Adicionar</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

django-dashboard-kit/apps/templates/home/lista_atividades.html
{% extends "layouts/base.html" %}

{% block title %} Atividades de {{ cliente.nome }} {% endblock %}

{% block content %}
<style>
    .activity-item {
        display: flex;
        justify-content: space-between;
        align-items: center;
        padding: 10px;
        margin-bottom: 10px;
        border-radius: 5px;
        background-color: #f9f9f9;
        box-shadow: 0 1px 3px rgba(0, 0, 0, 0.1);
    }
    
    .activity-item:nth-child(odd) {
        background-color: #f1f1f1;
    }
    
    .activity-pendente {
        border-left: 5px solid #ff6b6b;
    }
    
    .activity-concluida {
        border-left: 5px solid #4caf50;
    }
    
    .activity-aguardando_usuario {
        border-left: 5px solid #ffeb3b;
    }
    
    .activity-details {
        flex-grow: 1;
    }
    
    .activity-status {
        font-weight: bold;
        margin-left: 10px;
        color: #333;
        padding: 2px 5px;
        border-radius: 3px;
    }
    
    .status-pendente {
        background-color: #ff6b6b;
        color: #fff;
    }
    
    .status-concluida {
        background-color: #4caf50;
        color: #fff;
    }
    
    .status-aguardando_usuario {
        background-color: #ffeb3b;
        color: #000;
    }
    
    .activity-date {
        font-size: 0.9em;
        color: #888;
    }
    
    .activity-actions {
        display: flex;
        gap: 5px;
    }
    
    .delete-btn i.material-icons {
        vertical-align: middle;
    }

    .input-icon {
        cursor: pointer;
    }

    .form-group.position-relative {
        width: auto;
        display: flex;
        align-items: center;
    }

    #calendar-icon, #filter-icon {
        font-size: 24px;
        color: #000000;
        margin-right: 10px;
    }

    .btn-icon {
        display: flex;
        align-items: center;
        justify-content: center;
        height: 40px;
        padding: 0 10px;
        background-color: #edf0f3; /* Cor de fundo */
        border-radius: 5px;
        color: #fff; /* Cor do texto */
        border: none;
        box-shadow: none; /* Remove qualquer sombra */
        outline: none; /* Remove o contorno */
        margin: 0; /* Remove margens */
        background: none; /* Remove fundo padrão */
    }

    .btn-icon i {
        font-size: 18px;
        color: #fff; /* Cor do ícone */
        display: flex;
        align-items: center;
        justify-content: center;
        border: none; /* Remove a borda */
        box-shadow: none; /* Remove qualquer sombra */
        outline: none; /* Remove o contorno */
    }

    .btn-icon:focus, .btn-icon:active {
        background-color: #a4a3a5; /* Cor de fundo ao focar ou ativar */
        border: none; /* Remove a borda ao focar ou ativar */
        box-shadow: none; /* Remove qualquer sombra ao focar ou ativar */
        outline: none; /* Remove o contorno ao focar ou ativar */
    }

    .btn-icon:hover {
        background-color: #a4a3a5; /* Cor de fundo ao passar o mouse */
    }

    .flatpickr-calendar {
        z-index: 9999;
    }
</style>
<div class="pc-container">
    <div class="pcoded-content">
        <div class="page-header">
            <div class="page-block">
                <div class="row align-items-center">
                    <div class="col-md-6">
                        <div class="page-header-title">
                            <h5 class="m-b-10">Atividades de {{ cliente.nome }}</h5>
                        </div>
                        <ul class="breadcrumb">
                            <li class="breadcrumb-item"><a href="{% url 'home:home' %}">Home</a></li>
                            <li class="breadcrumb-item"><a href="{% url 'home:lista_clientes' %}">Clientes</a></li>
                            <li class="breadcrumb-item">{{ cliente.nome }}</li>
                            <li class="breadcrumb-item active">Atividades</li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-body">
                        <h6>Atividades</h6>
                        <form method="get" action="{% url 'home:lista_atividades' cliente.id %}" class="d-flex align-items-center">
                            <div class="form-group position-relative mb-0 mr-2">
                                <input type="text" id="date_range" name="date_range" class="form-control" style="display: none;">
                                <span class="input-icon" id="calendar-icon-wrapper" style="position: relative; display: inline-block;">
                                    <i class="fas fa-calendar-alt" id="calendar-icon"></i>
                                </span>
                            </div>
                            <button type="submit" class="btn btn-primary btn-icon">
                                <i class="fas fa-filter" id="filter-icon"></i> Filtrar
                            </button>
                        </form>
                        {% if not atividades_encontradas %}
                            <div class="alert alert-warning mt-4">
                                Nenhuma atividade encontrada para o período selecionado.
                            </div>
                        {% else %}
                            <ul class="activity-list mt-4">
                                {% for atividade in atividades %}
                                <li class="activity-item activity-{{ atividade.status }}">
                                    <div class="activity-details">
                                        <span class="activity-description">{{ atividade.descricao }}</span>
                                        <span class="activity-status status-{{ atividade.status }}">{{ atividade.get_status_display }}</span>
                                        <div class="activity-date">{{ atividade.criado_em|date:"d/m/Y H:i" }}</div>
                                    </div>
                                    <div class="activity-actions">
                                        <a href="{% url 'home:editar_atividade' cliente.id atividade.id %}" class="btn btn-warning btn-sm"><i class="fas fa-edit"></i></a>
                                        <form method="post" action="{% url 'home:excluir_atividade' cliente.id atividade.id %}" style="display: inline;">
                                            {% csrf_token %}
                                            <button type="submit" class="delete-btn btn btn-danger btn-sm"><i class="fas fa-trash"></i></button>
                                        </form>
                                    </div>
                                </li>
                                {% endfor %}
                            </ul>
                        {% endif %}
                        <a href="{% url 'home:adicionar_atividade' cliente.id %}" class="add-activity-btn btn btn-primary">Adicionar Atividade</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<script src="https://cdn.jsdelivr.net/npm/flatpickr"></script>
<script src="https://cdn.jsdelivr.net/npm/flatpickr/dist/l10n/pt.js"></script>
<script>
    // Inicializa o calendário e configura o comportamento de clique fora
    document.getElementById('calendar-icon').addEventListener('click', function(event) {
        event.stopPropagation();
        flatpickr("#date_range", {
            mode: "range",
            dateFormat: "Y-m-d",
            locale: "pt",
            altInput: true,
            altFormat: "j F, Y",
            onClose: function(selectedDates, dateStr, instance) {
                document.getElementById('date_range').style.display = 'block';
                instance.calendarContainer.style.zIndex = 9999;
            }
        }).open();
    });

    // Fecha o calendário ao clicar fora
    document.addEventListener('click', function(event) {
        var calendar = document.querySelector('.flatpickr-calendar');
        var calendarIcon = document.getElementById('calendar-icon');
        if (calendar && !calendar.contains(event.target) && event.target !== calendarIcon) {
            calendar._flatpickr.close();
            document.getElementById('date_range').style.display = 'none';
        }
    });
</script>
{% endblock %}

django-dashboard-kit/apps/templates/home/lista_clientes.html
{% extends "layouts/base.html" %}

{% load static %}

{% block title %} Lista de Clientes {% endblock %}
{% block stylesheets %}
    <link rel="stylesheet" href=" {% static 'assets/css/client_list.css' %}">
{% endblock stylesheets %}
{% block content %}
<!-- [ Main Content ] start -->
<div class="pc-container">
    <div class="pcoded-content">
        <div class="page-header">
            <div class="page-block">
                <div class="row align-items-center">
                    <div class="col-md-6 col-12">
                        <div class="page-header-title">
                            <h5 class="m-b-10">Clientes</h5>
                        </div>s
                        <ul class="breadcrumb">
                            <li class="breadcrumb-item"><a href="{% url 'home:home' %}">Home</a></li>
                            <li class="breadcrumb-item">Clientes</li>
                        </ul>
                    </div>
                    <div class="col-md-6 col-12 text-right add-button-container">
                        <a href="{% url 'home:adicionar_cliente' %}" class="btn btn-primary btn-icon" aria-label="Adicionar Cliente">
                            <i class="material-icons" aria-hidden="true">add</i>
                        </a>
                    </div>
                </div>
            </div>
        </div>


        
        <div class="card-container">
            {% for cliente in clientes %}
            <div class="card">
                {% if cliente.foto %}
                    <img src="{{ cliente.foto.url }}" class="card-img-top" alt="Foto de {{ cliente.nome }}">
                {% endif %}
                <div class="card-body">
                    <h5 class="card-title">{{ cliente.nome }}</h5>
                    <p class="card-text">{{ cliente.descricao }}</p>
                    <a href="{% url 'home:detalhe_cliente' cliente.id %}" class="btn btn-primary" aria-label="Ver detalhes de {{ cliente.nome }}">Ver Detalhes</a>
                </div>
            </div>
            {% endfor %}
        </div>
        {% include 'includes/pagination.html' %}
    </div>
</div>
<!-- [ Main Content ] end -->
{% endblock %}