django-dashboard-kit/apps/analise_pico/urls.py
from django.urls import path
from .views import AnalisePicoView
from . import views

app_name = 'analise_pico'

urlpatterns = [
    path('pico/', AnalisePicoView.as_view(), name='pico_movimento'),
]

django-dashboard-kit/apps/home/urls.py
from django.urls import path, include
from django.shortcuts import redirect
from rest_framework.routers import DefaultRouter
from .views import ( IndexView, ClienteListView, ClienteDetailView, lista_atividades,
    adicionar_atividade, excluir_atividade, editar_atividade,
    adicionar_cliente, ServicoCreateView, editar_servico, ServicoDeleteView,
    ProjectCreateView, ProjectListView, ProjectUpdateView, ProjectDeleteView
)
from .views_api import (
    CompanyViewSet, TipoServicoViewSet, StatusViewSet,
    ClienteViewSet, ServicoViewSet, AtividadeViewSet
)

app_name = 'home'

# Criar um roteador para as rotas da API
router = DefaultRouter()
router.register(r'companies', CompanyViewSet)
router.register(r'tipo-servicos', TipoServicoViewSet)
router.register(r'status', StatusViewSet)
router.register(r'clientes', ClienteViewSet)
router.register(r'servicos', ServicoViewSet)
router.register(r'atividades', AtividadeViewSet)

urlpatterns = [
    # Rotas da web
    path('', lambda request: redirect('ligobots:dashboard_kpi_ura'), name='home'),
    path('lista_clientes/', ClienteListView.as_view(), name='lista_clientes'),
    path('detalhe_cliente/<int:pk>/', ClienteDetailView.as_view(), name='detalhe_cliente'),

    path('cliente/<int:cliente_id>/atividades/', lista_atividades, name='lista_atividades'),
    path('cliente/<int:cliente_id>/atividade/adicionar/', adicionar_atividade, name='adicionar_atividade'),
    path('cliente/<int:cliente_id>/atividade/<int:atividade_id>/excluir/', excluir_atividade, name='excluir_atividade'),
    path('cliente/<int:cliente_id>/atividade/<int:atividade_id>/editar/', editar_atividade, name='editar_atividade'),

    path('clientes/adicionar/', adicionar_cliente, name='adicionar_cliente'),

    path('servico/editar/<int:id>/', editar_servico, name='editar_servico'),
    path('cliente/<int:cliente_id>/servico/adicionar/', ServicoCreateView.as_view(), name='adicionar_servico'),
    path('cliente/<int:cliente_id>/servico/<int:pk>/excluir/', ServicoDeleteView.as_view(), name='excluir_servico'),

    path('projetos/', ProjectListView.as_view(), name='lista_projetos'),
    path('projetos/add/', ProjectCreateView.as_view(), name='adicionar_projeto'),
    path('projeto/<int:pk>/editar/', ProjectUpdateView.as_view(), name='editar_projeto'),
    path('projeto/<int:pk>/excluir/', ProjectDeleteView.as_view(), name='excluir_projeto'),

    # Rotas da API
    path('api/', include(router.urls)),
]

django-dashboard-kit/apps/ligobots/urls.py
from django.urls import path, include
from rest_framework.routers import DefaultRouter
from .views import (DashboardKpiUraView, RelatorioURAView)
from .views_api import (
    EmpresasOminiViewSet, PerfilUsuarioViewSet, LicencaViewSet, 
    CanalOminiViewSet, BotViewSet, BotCanalViewSet, LicencaUsuarioViewSet,
    URAViewSet, RPAViewSet, empresas_view, quantidade_mensagens_por_bot_e_canal_view, sessoes_view,
    atividade_agentes_ura_view, indicador_de_desempenho_por_fila_de_URA_view, tempo_medio_servico_por_atendente_view,
    indicadores_de_desempenho_view
)
app_name = 'ligobots'

# Criar um roteador para as rotas da API
router = DefaultRouter()
router.register(r'empresas', EmpresasOminiViewSet)
router.register(r'perfils', PerfilUsuarioViewSet)
router.register(r'licencas', LicencaViewSet)
router.register(r'canais', CanalOminiViewSet)
router.register(r'bots', BotViewSet)
router.register(r'bot-canais', BotCanalViewSet)
router.register(r'licenca-usuarios', LicencaUsuarioViewSet)
router.register(r'uras', URAViewSet)
router.register(r'rpas', RPAViewSet)

urlpatterns = [
    # Rotas da web
    path('dashboard-kpi-ura/', DashboardKpiUraView.as_view(), name='dashboard_kpi_ura'),
    path('relatorio-ura/', RelatorioURAView.as_view(), name='relatorio_ura'),
    
    # Rotas da API
    path('api/', include(router.urls)),
    path('api/empresas/', empresas_view, name='fetch_empresas'),
    path('api/quantidade-mensagens-por-bot-e-canal/', quantidade_mensagens_por_bot_e_canal_view, name='quantidade_mensagens_por_bot_e_canal'),
    path('api/sessoes/', sessoes_view, name='sessoes'),
    path('api/atividade-agentes-ura/', atividade_agentes_ura_view, name='atividade-agentes-ura'),
    path('api/indicador_de_desempenho_por_fila_de_URA/', indicador_de_desempenho_por_fila_de_URA_view, name='indicador_de_desempenho_por_fila_de_URA'),
    path('api/tempo-medio-servico-por-atendente/', tempo_medio_servico_por_atendente_view, name='tempo_medio_servico_por_atendente'),
    path('api/indicadores-de-desempenho/', indicadores_de_desempenho_view, name='indicadores_de_desempenho'),
    
]

django-dashboard-kit/apps/relatorios/urls.py
from django.urls import path
from .views import LigacoesAbandonadasView, verificar_status_task, UraJornadaView, LeiaView
from .views_api import (
    obter_chamadas_ivr_view
)

app_name = 'relatorios'

urlpatterns = [
    # URL para exibir o formulário e iniciar o processamento das ligações abandonadas
    path('api/obter_chamadas_ivr/', obter_chamadas_ivr_view, name='obter_chamadas_ivr'),
    path('abandonadas-ura/', LigacoesAbandonadasView.as_view(), name='abandonadas_ura'),
    path('jornada-ura/', UraJornadaView.as_view(), name='jornada_ura'),
    path('leia/', LeiaView.as_view(), name='leia'),
    # URL para verificar o progresso da task Celery
    path('celery-status/<str:task_id>/', verificar_status_task, name='celery_status'),
]

django-dashboard-kit/core/urls.py
# -*- encoding: utf-8 -*-

from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),          
    path("", include("apps.authentication.urls")), 
    path("", include("apps.home.urls")),
    path('ligobots/', include('apps.ligobots.urls', namespace='ligobots')),
    path('relatorios/', include('apps.relatorios.urls', namespace='relatorios')),
    path('analise-pico/', include('apps.analise_pico.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

django-dashboard-kit/apps/templates/includes/navigation.html
<!-- [ Header ] start -->
<header class="pc-header ">
    <div class="header-wrapper">
        <div class="me-auto pc-mob-drp">
            <ul class="list-unstyled">
                <li class="dropdown pc-h-item">
                    <a class="pc-head-link active dropdown-toggle arrow-none me-0" data-bs-toggle="dropdown" href="#"
                        role="button" aria-haspopup="false" aria-expanded="false">
                        Nível
                    </a>
                    <div class="dropdown-menu pc-h-dropdown">
                        <a href="#!" class="dropdown-item">
                            <i class="material-icons-two-tone">account_circle</i>
                            <span>Minha conta</span>
                        </a>
                        <a href="#!" class="dropdown-item">
                            <i class="material-icons-two-tone">settings</i>
                            <span>Configurações</span>
                        </a>
                        <a href="#" class="dropdown-item" onclick="event.preventDefault(); document.getElementById('logout-form').submit();">
                            <i class="material-icons-two-tone">chrome_reader_mode</i>
                            <span>Sair</span>
                        </a>
                    </div>
                </li>
            </ul>
        </div>

        <div class="ms-auto">
            <ul class="list-unstyled">
                <li class="dropdown pc-h-item">
                    <a class="pc-head-link dropdown-toggle arrow-none me-0" data-bs-toggle="dropdown" href="#" role="button"
                        aria-haspopup="false" aria-expanded="false">
                        <i class="material-icons-two-tone">search</i>
                    </a>
                    <div class="dropdown-menu dropdown-menu-end pc-h-dropdown drp-search">
                        <form class="px-3">
                            <div class="form-group mb-0 d-flex align-items-center">
                                <i data-feather="search"></i>
                                <input type="search" class="form-control border-0 shadow-none" placeholder="Search here. . .">
                            </div>
                        </form>
                    </div>
                </li>
                <li class="dropdown pc-h-item">
                    <a class="pc-head-link dropdown-toggle arrow-none me-0" data-bs-toggle="dropdown" href="#" role="button"
                        aria-haspopup="false" aria-expanded="false">
                        <img src="/static/assets/images/user/avatar-1.jpg" alt="user-image" class="user-avtar">
                        <span>
                            <span class="user-name">
                                {{ request.user.username }}
                            </span>
                            <span class="user-desc">
                                {{ request.user.email }}
                            </span>
                        </span>
                    </a>
                    <div class="dropdown-menu dropdown-menu-end pc-h-dropdown">
                        <div class=" dropdown-header">
                            <h5 class="text-overflow m-0">
                                <span class="badge bg-light-primary">
                                    <a href="#"
                                       target="_blank">
                                    Conta
                                    </a>
                                </span>
                            </h5>
                        </div>

                        <a href="#" class="dropdown-item" onclick="event.preventDefault(); document.getElementById('logout-form').submit();">
                            <i class="material-icons-two-tone">chrome_reader_mode</i>
                            <span>Sair</span>
                        </a>
                    </div>
                </li>
            </ul>
        </div>
    </div>
</header>
<!-- [ Header ] end -->

<!-- Formulário de Logout -->
<form id="logout-form" action="{% url 'authentication:logout' %}" method="POST" style="display: none;">
    {% csrf_token %}
</form>

django-dashboard-kit/apps/templates/includes/pagination.html
<nav aria-label="Page navigation">
    <ul class="pagination justify-content-center">
        {% if page_obj.has_previous %}
        <li class="page-item">
            <a class="page-link" href="?page=1" aria-label="First">
                <span aria-hidden="true">&laquo;</span>
            </a>
        </li>
        <li class="page-item">
            <a class="page-link" href="?page={{ page_obj.previous_page_number }}" aria-label="Previous">
                <span aria-hidden="true">&lsaquo;</span>
            </a>
        </li>
        {% endif %}
        {% for num in page_obj.paginator.page_range %}
            {% if page_obj.number == num %}
                <li class="page-item active"><a class="page-link">{{ num }}</a></li>
            {% elif num > page_obj.number|add:'-3' and num < page_obj.number|add:'3' %}
                <li class="page-item"><a class="page-link" href="?page={{ num }}">{{ num }}</a></li>
            {% endif %}
        {% endfor %}
        {% if page_obj.has_next %}
        <li class="page-item">
            <a class="page-link" href="?page={{ page_obj.next_page_number }}" aria-label="Next">
                <span aria-hidden="true">&rsaquo;</span>
            </a>
        </li>
        <li class="page-item">
            <a class="page-link" href="?page={{ page_obj.paginator.num_pages }}" aria-label="Last">
                <span aria-hidden="true">&raquo;</span>
            </a>
        </li>
        {% endif %}
    </ul>
</nav>

django-dashboard-kit/apps/templates/includes/preloader.html
	<div class="loader-bg">
		<div class="loader-track">
			<div class="loader-fill"></div>
		</div>
	</div>

    

django-dashboard-kit/apps/templates/includes/promo-fixed-button.html
<div class="fixed-button active"><a
        href="https://appseed.us/product/django-dashboard-kit-pro" target="_blank"
        class="btn btn-md btn-success"><i class="material-icons-two-tone text-white">shopping_cart</i> 
        Upgrade to Pro</a>
</div>

django-dashboard-kit/apps/templates/includes/scripts.html
    <!-- Required Js -->
    <script src="/static/assets/js/vendor-all.js"></script>
    <script src="/static/assets/js/plugins/bootstrap.min.js"></script>
    <script src="/static/assets/js/plugins/feather.min.js"></script>
    {% comment %} <script src="/static/assets/js/pcoded.js"></script> {% endcomment %}

django-dashboard-kit/apps/templates/includes/sidebar.html
	<!-- [ navigation menu ] start -->
	{% load static %}
	<div class="sidebar close">
		<i class="bx bx-menu" id="sidebarToggle"></i>
		<div class="logo-details">
			<img src="{% static 'assets/images/user/LogoVertical_Wtime_EscritoBranco.png' %}" alt="Wtime Logo" class="logo">
			<span class="logo_name">time DashboardX</span>
		</div>
		
		<ul class="nav-links">
			{% if user.is_superuser %}
				<li>
					<a href="/" class="active">
						<i class="fas fa-th-large"></i>
						<span class="link_name">Dashboard</span>
					</a>
					<ul class="sub-menu blank">
						<li><a class="link_name" href="/">Dashboard</a></li>
					</ul>
				</li>
				<li>
					<div class="iocn-link">
						<a href="#">
							<i class="fas fa-briefcase"></i>
							<span class="link_name">Clientes</span>
						</a>
						<i class="bx bxs-chevron-down arrow"></i>
					</div>
					<ul class="sub-menu">
						<li><a href="{% url 'home:lista_clientes' %}">Lista de Clientes</a></li>
					</ul>
				</li>
				<li>
					<a href="{% url 'home:lista_projetos' %}">
						<i class="fas fa-tasks"></i>
						<span class="link_name">Projetos</span>
					</a>
					<ul class="sub-menu blank">
						<li><a class="link_name" href="{% url 'home:lista_projetos' %}">Projetos</a></li>
					</ul>
				</li>
			{% endif %}
			<li>
				<a href="{% url 'ligobots:dashboard_kpi_ura' %}">
					<i class="fas fa-tachometer-alt"></i>
					<span class="link_name">Relatórios de KPIS</span>
				</a>
				<ul class="sub-menu blank">
					<li><a class="link_name" href="{% url 'ligobots:dashboard_kpi_ura' %}">Relatórios de KPIS</a></li>
				</ul>
			</li>
			<li>
				<a href="{% url 'ligobots:relatorio_ura' %}">
					<i class="fas fa-headset"></i> 
					<span class="link_name">Relatórios de URA</span>
				</a>
				<ul class="sub-menu blank">
					<li><a class="link_name" href="{% url 'ligobots:relatorio_ura' %}">Relatórios de URA</a></li>
				</ul>
			</li>
			<li>
				<a href="{% url 'relatorios:abandonadas_ura' %}">
					<i class="fas fa-phone-slash"></i>
					<span class="link_name">Abandonos URA</span>
				</a>
				<ul class="sub-menu blank">
					<li><a class="link_name" href="{% url 'relatorios:abandonadas_ura' %}">Abandonos URA</a></li>
				</ul>
			</li>
			<li>
				<a href="{% url 'relatorios:jornada_ura' %}">
					<i class="fas fa-route"></i> 
					<span class="link_name">Jornada da URA</span>
				</a>
				<ul class="sub-menu blank">
					<li><a class="link_name" href="{% url 'relatorios:jornada_ura' %}">Jornada da URA</a></li>
				</ul>
			</li>
			<li>
				<div class="profile-details">
					<div class="profile-content">
						<img src="{% static 'assets/images/auth/auth-side.jpg' %}" alt="profileImg">
					</div>
					<div class="name-job">
						<div class="profile_name">Wtime</div>
						<div class="job">Dashboard</div>
					</div>
					<i class="bx bx-log-out"></i>
				</div>
			</li>
			<li>
				<a href="{% url 'analise_pico:pico_movimento' %}">
					<i class="fas fa-chart-line"></i>
					<span class="link_name">Análise de Picos</span>
				</a>
				<ul class="sub-menu blank">
					<li><a class="link_name" href="{% url 'analise_pico:pico_movimento' %}">Análise de Picos</a></li>
				</ul>
			</li>
			<!-- Nova opção para Curadoria de Fala -->
			<li>
				<a href="{% url 'relatorios:leia' %}"> 
					<i class="fas fa-brain"></i> 
					<span class="link_name">Le-IA</span> 
				</a>
				<ul class="sub-menu blank">
					<li><a class="link_name" href="{% url 'relatorios:leia' %}">Le-IA</a></li>
				</ul>
			</li>
		</ul>
	</div>
	<!-- [ navigation menu ] end -->